/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/efVjaAxSGLS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Dialog, DialogTrigger, DialogContent, DialogFooter, DialogClose } from "@/components/ui/dialog"

export function blogpage() {
  const [isDarkMode, setIsDarkMode] = useState(false)
  return (
    <div className={`flex min-h-screen w-full flex-col bg-background ${isDarkMode ? "dark" : ""}`}>
      <header className="sticky top-0 z-40 border-b bg-background">
        <div className="container flex h-14 items-center justify-between px-4 md:px-6">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <MountainIcon className="h-6 w-6" />
            <span className="text-lg font-semibold">Acme Blog</span>
          </Link>
          <nav className="hidden items-center gap-4 md:flex">
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              About
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Blog
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" className="md:hidden" onClick={() => setIsDarkMode(!isDarkMode)}>
              {isDarkMode ? <SunIcon className="h-6 w-6" /> : <MoonIcon className="h-6 w-6" />}
              <span className="sr-only">Toggle dark mode</span>
            </Button>
            <Button variant="outline" size="icon" className="md:hidden">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation</span>
            </Button>
          </div>
        </div>
      </header>
      <div className="flex-1">
        <div className="container grid grid-cols-1 gap-8 py-8 md:grid-cols-[250px_1fr_250px] md:py-12 lg:py-16">
          <aside className="sticky top-20 hidden h-[calc(100vh-5rem)] max-h-[calc(100vh-5rem)] overflow-y-auto rounded-lg border bg-background p-4 md:block">
            <nav className="space-y-2">
              <h4 className="text-sm font-semibold">Table of Contents</h4>
              <div className="space-y-1">
                <Link href="#" className="block text-sm hover:underline" prefetch={false}>
                  Introduction
                </Link>
                <Link href="#" className="block text-sm hover:underline" prefetch={false}>
                  Step 1: Choose a Business Structure
                </Link>
                <Link href="#" className="block text-sm hover:underline" prefetch={false}>
                  Step 2: Register Your Business
                </Link>
                <Link href="#" className="block text-sm hover:underline" prefetch={false}>
                  Step 3: Obtain Necessary Licenses and Permits
                </Link>
                <Link href="#" className="block text-sm hover:underline" prefetch={false}>
                  Step 4: Secure Funding
                </Link>
                <Link href="#" className="block text-sm hover:underline" prefetch={false}>
                  Step 5: Build Your Brand
                </Link>
                <Link href="#" className="block text-sm hover:underline" prefetch={false}>
                  Conclusion
                </Link>
              </div>
            </nav>
          </aside>
          <article className="prose prose-gray max-w-none mx-auto lg:max-w-6xl dark:prose-invert">
            <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl lg:leading-[3.5rem]">
              How to Start a Business in the USA
            </h1>
            <p className="text-muted-foreground">Published on September 2, 2024</p>
            <section id="introduction">
              <h2>Introduction</h2>
              <p>
                Starting a business in the USA can be an exciting and rewarding journey, but it also comes with its fair
                share of challenges. From choosing the right business structure to securing funding and building a
                strong brand, the process can be daunting for first-time entrepreneurs. In this comprehensive guide,
                we'll walk you through the essential steps to start a successful business in the United States.
              </p>
            </section>
            <section id="step-1">
              <h2>Step 1: Choose a Business Structure</h2>
              <p>
                The first step in starting a business in the USA is to determine the appropriate legal structure for
                your company. The most common business structures are sole proprietorship, partnership, limited
                liability company (LLC), and corporation. Each structure has its own advantages and disadvantages, so
                it's important to carefully consider your specific needs and goals before making a decision.
              </p>
              <p>
                For example, a sole proprietorship is the simplest and most common business structure, but it also means
                you're personally liable for all business debts and obligations. On the other hand, an LLC offers
                limited liability protection and more flexibility in terms of taxation and management structure.
              </p>
            </section>
            <section id="step-2">
              <h2>Step 2: Register Your Business</h2>
              <p>
                Once you've chosen your business structure, the next step is to register your company with the
                appropriate state and federal authorities. This typically involves filing articles of incorporation or
                organization, obtaining a federal employer identification number (EIN), and registering for state and
                local business licenses and permits.
              </p>
              <p>
                The specific registration requirements will vary depending on your location and the type of business
                you're starting, so it's important to research the regulations in your state and local area. You may
                also need to obtain additional licenses or permits, such as a sales tax permit or a zoning permit,
                depending on the nature of your business.
              </p>
            </section>
            <section id="step-3">
              <h2>Step 3: Obtain Necessary Licenses and Permits</h2>
              <p>
                In addition to registering your business, you'll also need to obtain the necessary licenses and permits
                to operate legally in your state and local area. This can include things like a business license, a
                sales tax permit, a professional license (if your business requires one), and any industry-specific
                permits or certifications.
              </p>
              <p>
                The specific requirements will vary depending on your location and the type of business you're starting,
                so it's important to research the regulations in your area and comply with all applicable laws and
                regulations.
              </p>
            </section>
            <section id="step-4">
              <h2>Step 4: Secure Funding</h2>
              <p>
                Starting a business requires capital, and securing the necessary funding can be one of the biggest
                challenges for new entrepreneurs. There are several options for funding your business, including
                personal savings, loans from friends and family, small business loans, angel investors, and venture
                capital.
              </p>
              <p>
                When seeking funding, it's important to have a solid business plan that outlines your goals, strategies,
                and financial projections. This will help you demonstrate the viability of your business and increase
                your chances of securing the necessary funding.
              </p>
            </section>
            <section id="step-5">
              <h2>Step 5: Build Your Brand</h2>
              <p>
                Finally, once you've taken care of the legal and financial aspects of starting your business, it's time
                to focus on building your brand. This includes developing a strong visual identity, creating a
                compelling website, and developing a marketing strategy to reach your target audience.
              </p>
              <p>
                Building a strong brand can help you stand out in a crowded market and establish trust and loyalty with
                your customers. It's important to be consistent in your messaging and branding across all of your
                marketing channels, from your website to your social media profiles and printed materials.
              </p>
            </section>
            <section id="conclusion">
              <h2>Conclusion</h2>
              <p>
                Starting a business in the USA can be a challenging but rewarding endeavor. By following the steps
                outlined in this guide, you can increase your chances of success and build a thriving business that
                meets the needs of your customers and achieves your financial goals.
              </p>
              <p>
                Remember, starting a business is a journey, and it's important to be patient, persistent, and adaptable
                as you navigate the various challenges and opportunities that come your way. With the right mindset and
                a solid plan, you can turn your entrepreneurial dreams into reality.
              </p>
            </section>
          </article>
          <aside className="sticky top-20 hidden h-[calc(100vh-5rem)] max-h-[calc(100vh-5rem)] overflow-y-auto rounded-lg bg-background p-4 md:block">
            <div className="space-y-4">
              <h4 className="text-sm font-semibold">Let's Talk</h4>
              <p className="text-sm text-muted-foreground">
                Have a question or need help starting your business? Schedule a consultation with our experts.
              </p>
              <Button>Schedule a Call</Button>
            </div>
          </aside>
        </div>
      </div>
      <footer className="bg-muted p-6 md:py-12">
        <div className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
          <div className="grid gap-1">
            <h3 className="font-semibold">Company</h3>
            <Link href="#" prefetch={false}>
              About Us
            </Link>
            <Link href="#" prefetch={false}>
              Our Team
            </Link>
            <Link href="#" prefetch={false}>
              Careers
            </Link>
            <Link href="#" prefetch={false}>
              News
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Products</h3>
            <Link href="#" prefetch={false}>
              Men
            </Link>
            <Link href="#" prefetch={false}>
              Women
            </Link>
            <Link href="#" prefetch={false}>
              Kids
            </Link>
            <Link href="#" prefetch={false}>
              Accessories
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Resources</h3>
            <Link href="#" prefetch={false}>
              Blog
            </Link>
            <Link href="#" prefetch={false}>
              Community
            </Link>
            <Link href="#" prefetch={false}>
              Support
            </Link>
            <Link href="#" prefetch={false}>
              FAQs
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Legal</h3>
            <Link href="#" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" prefetch={false}>
              Cookie Policy
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Contact</h3>
            <Link href="#" prefetch={false}>
              Support
            </Link>
            <Link href="#" prefetch={false}>
              Sales
            </Link>
            <Link href="#" prefetch={false}>
              Press
            </Link>
            <Link href="#" prefetch={false}>
              Partnerships
            </Link>
          </div>
        </div>
      </footer>
      <Dialog>
        <DialogTrigger asChild>
          <div className="fixed bottom-0 left-0 right-0 z-50 bg-background shadow-lg md:hidden">
            <div className="container flex items-center justify-between px-4 py-4">
              <div className="space-y-1">
                <h4 className="text-lg font-semibold">Free Business Plan Template</h4>
                <p className="text-sm text-muted-foreground">
                  Sign up to get a free business plan template to help you start your business.
                </p>
              </div>
              <Button>Sign Up</Button>
            </div>
          </div>
        </DialogTrigger>
        <DialogContent className="sm:max-w-[425px]">
          <div className="flex flex-col items-center justify-center gap-4 py-8">
            <CircleCheckIcon className="size-12 text-green-500" />
            <p className="text-lg font-medium">Thank you for signing up!</p>
            <p className="text-muted-foreground">
              We've sent you the free business plan template. Check your email for more details.
            </p>
          </div>
          <DialogFooter>
            <div>
              <Button type="button">Close</Button>
            </div>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

function CircleCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MoonIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}
